(let ()
	(let ((x 1))
		(let ((y 2) (lst (cons #t '())))
			(let ((z (box (cdr lst))) (a 3))
				#t)
			(let ((b 4) (c (box y)))
				#f)))
	(for ([x (in-range  1 1000001 1)])
		(displayln x))
	(displayln #t))
